kind: pipeline
type: docker
name: the-weekend-bot

steps:
  - name: build and test
    image: adoptopenjdk/openjdk11:jdk-11.0.11_9
    environment:
      GRADLE_USER_HOME: .gradle
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false
    commands:
      - ./gradlew clean build buildLayers --console rich

  - name: docker build dry run
    image: plugins/docker
    when:
      event:
        - pull_request
      branch:
        - main
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: http://docker.internal.mapes.info
      insecure: true
      dry_run: true
      repo: docker.internal.mapes.info/the-weekend-bot
      mirror: https://docker.mapes.info
      tags: 'b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}'

  - name: docker publish snapshot
    image: plugins/docker
    when:
      event:
        - push
      branch:
        - main
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: http://docker.internal.mapes.info
      insecure: true
      repo: docker.internal.mapes.info/the-weekend-bot
      mirror: https://docker.mapes.info
      tags: 'b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}'

  - name: docker publish release
    image: plugins/docker
    when:
      event:
        - tag
      branch:
        - main
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: http://docker.internal.mapes.info
      insecure: true
      repo: docker.internal.mapes.info/the-weekend-bot
      mirror: https://docker.mapes.info
      tags: '${DRONE_TAG}'