version: "1"

steps:

  - name: build
    image: eclipse-temurin:11.0.13_8-jdk-alpine
    pull: not_present
    commands:
      - ./gradlew clean build buildLayers

  - name: build image dry run
    image: target/vela-kaniko:v0.7.1
    environment:
      - container=docker
    parameters:
      dry_run: true
      repo: docker.internal.mapes.info/the-weekend-bot
      tags:
        - dry_run
    ruleset:
      event: [pull_request]
      branch: [main]

  - name: build tag image
    image: target/vela-kaniko:v0.7.1
    environment:
      - container=docker
    secrets:
      - source: docker_username
        target: parameter_username
      - source: docker_password
        target: parameter_password
    parameters:
      repo: docker.io/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - "b${VELA_BUILD_NUMBER}-${VELA_BUILD_COMMIT:0:8}"
    ruleset:
      event: push
      branch: main

  - name: build tag image
    image: target/vela-kaniko:v0.7.1
    environment:
      - container=docker
    secrets:
      - source: docker_username
        target: parameter_username
      - source: docker_password
        target: parameter_password
    parameters:
      repo: docker.io/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - "${VELA_BUILD_TAG:##v}"
    ruleset:
      event: tag

secrets:
  - name: docker_username
    type: org
    key: tmapes/docker_username
    engine: native
  - name: docker_password
    type: org
    key: tmapes/docker_password
    engine: native
