version: "1"

metadata:
  auto_cancel:
    running: true

steps:

  - name: build
    image: eclipse-temurin:17.0.11_9-jdk-alpine
    pull: not_present
    commands:
      - ./gradlew clean build buildLayers

  - name: build image dry run
    image: target/vela-kaniko:v0.17.0
    parameters:
      dry_run: true
      repo: index.docker.io/tjmapes/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - dry_run
    ruleset:
      event: [ pull_request ]
      branch: [ main ]

  - name: build snapshot image
    image: target/vela-kaniko:v0.17.0
    secrets: [ docker_username, docker_password ]
    parameters:
      registry: https://index.docker.io/v1/
      repo: index.docker.io/tjmapes/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - "b${VELA_BUILD_NUMBER}-${VELA_BUILD_COMMIT:0:8}"
    ruleset:
      event: push
      branch: main

  - name: build tag image
    image: target/vela-kaniko:v0.17.0
    secrets: [ docker_username, docker_password ]
    parameters:
      registry: https://index.docker.io/v1/
      repo: index.docker.io/tjmapes/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - "${VELA_BUILD_TAG:##v}"
    ruleset:
      event: tag

secrets:
  - name: docker_username
    type: org
    key: tmapes/docker_username
    engine: native
  - name: docker_password
    type: org
    key: tmapes/docker_password
    engine: native
