version: "1"

metadata:
  auto_cancel:
    running: true

steps:

  - name: build
    image: eclipse-temurin:21.0.5_11-jdk-alpine@sha256:4909fb9ab52e3ce1488cc6e6063da71a0f9f9833420cc254fe03bbe25daec9e0
    pull: not_present
    commands:
      - ./gradlew clean build

  - name: build image dry run
    image: target/vela-kaniko:v0.18.0@sha256:e8a34dc03399a6f126d301568811484e4d52eacb85049244866161934ee4bd60
    parameters:
      dry_run: true
      repo: index.docker.io/tjmapes/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - dry_run
    ruleset:
      event: [ pull_request ]
      branch: [ main ]

  - name: build snapshot image
    image: target/vela-kaniko:v0.18.0@sha256:e8a34dc03399a6f126d301568811484e4d52eacb85049244866161934ee4bd60
    secrets: [ docker_username, docker_password ]
    parameters:
      registry: https://index.docker.io/v1/
      repo: index.docker.io/tjmapes/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - "b${VELA_BUILD_NUMBER}-${VELA_BUILD_COMMIT:0:8}"
    ruleset:
      event: push
      branch: main

  - name: build tag image
    image: target/vela-kaniko:v0.18.0@sha256:e8a34dc03399a6f126d301568811484e4d52eacb85049244866161934ee4bd60
    secrets: [ docker_username, docker_password ]
    parameters:
      registry: https://index.docker.io/v1/
      repo: index.docker.io/tjmapes/the-weekend-bot
      mirror: docker.mapes.info
      tags:
        - "${VELA_BUILD_TAG:##v}"
    ruleset:
      event: tag

secrets:
  - name: docker_username
    type: org
    key: tmapes/docker_username
    engine: native
  - name: docker_password
    type: org
    key: tmapes/docker_password
    engine: native
