version: "3"
services:
  app:
    image: tjmapes/the-weekend-bot:b47-116995e9@sha256:3b782bf4b90c2aa2e692f8b05b9be46db57d46d7ddcbdc7b734f097960ea9153
    ports:
      - "8080:8080"
    volumes:
      - "./src/main/resources/application-local.yml:/app/resources/application-local.yml:ro"
    environment:
      - MICRONAUT_ENVIRONMENTS=local
      - DISCORD_SCHEDULE=0/10 * * * * *
  mongo:
    image: mongo:8.0.4@sha256:33d17eb9a1c27c6635d08f890cd075d0f9392c598eaad8c4461344ac5fbc7140
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movies
