version: "3"
services:
  app:
    image: tjmapes/the-weekend-bot:b47-116995e9
    ports:
      - "8080:8080"
    volumes:
      - "./src/main/resources/application-local.yml:/app/resources/application-local.yml:ro"
    environment:
      - MICRONAUT_ENVIRONMENTS=local
      - DISCORD_SCHEDULE=0/10 * * * * *
  mongo:
    image: mongo:7.0.11@sha256:8f9f843d383e358d9be2f172ba9d2455e8736f3c59b00330da1f1b44273ce267
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movies
