version: "3"
services:
  app:
    image: docker.internal.mapes.info/the-weekend-bot:b12-ddcc597e
    ports:
      - "8080:8080"
    volumes:
      - "./src/main/resources/application-local.yml:/app/resources/application-local.yml:ro"
    environment:
      - MICRONAUT_ENVIRONMENTS=local
      - DISCORD_SCHEDULE=0/10 * * * * *
  mongo:
    image: docker.mapes.info/mongo:4.2.8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movies
