version: "3"
services:
  app:
    image: tjmapes/the-weekend-bot:b47-116995e9@sha256:3b782bf4b90c2aa2e692f8b05b9be46db57d46d7ddcbdc7b734f097960ea9153
    ports:
      - "8080:8080"
    volumes:
      - "./src/main/resources/application-local.yml:/app/resources/application-local.yml:ro"
    environment:
      - MICRONAUT_ENVIRONMENTS=local
      - DISCORD_SCHEDULE=0/10 * * * * *
  mongo:
    image: mongo:8.0.4@sha256:4f93a84f7d4d8b1b6cb7e0c172d8a44b0bed9b399f207165ea19473bdb5a36b0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movies
