version: "3"
services:
  app:
    image: tjmapes/the-weekend-bot:b47-116995e9
    ports:
      - "8080:8080"
    volumes:
      - "./src/main/resources/application-local.yml:/app/resources/application-local.yml:ro"
    environment:
      - MICRONAUT_ENVIRONMENTS=local
      - DISCORD_SCHEDULE=0/10 * * * * *
  mongo:
    image: mongo:8.0.1@sha256:9342a9279a9841fc5f8192e49dcaaf9404e6bb3a90e8cf134eb96074830dd448
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movies
