name: Gradle build on push

on:
  push:
    branches: '*'
    tags-ignore: '*'

jobs:
  build:
    uses: ./.github/workflows/gradle_build.yml
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
